# This file configures the log shipping on filebeat to sendt log information from the performance log to an ELK stack
- type: log

  enabled: true

  paths:
    - /var/log/performance*.json
    - /data/jboss/tools/jboss-eap/standalone/log/performance*.json

  scan_frequency: 10s

  ### JSON configuration

  # Decode JSON options. Enable this if your logs are structured in JSON.
  # JSON key on which to apply the line filtering and multiline settings. This key
  # must be top level and its value must be string, otherwise it is ignored. If
  # no text key is defined, the line filtering and multiline features cannot be used.
  #json.message_key:

  # By default, the decoded JSON is placed under a "json" key in the output document.
  # If you enable this setting, the keys are copied top level in the output document.
  #json.keys_under_root: false
  json.keys_under_root: true

  # If keys_under_root and this setting are enabled, then the values from the decoded
  # JSON object overwrite the fields that Filebeat normally adds (type, source, offset, etc.)
  # in case of conflicts.
  #json.overwrite_keys: false
  json.overwrite_keys: true
  # this will make (among others) @timestamp to be overwritten when
  # specified in the JSON event line.

  # If this setting is enabled, Filebeat adds a "error.message" and "error.key: json" key in case of JSON
  # unmarshaling errors or when a text key is defined in the configuration but cannot
  # be used.
  #json.add_error_key: false
  json.add_error_key: true
