# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0
#https://github.com/bitnami/containers/blob/main/bitnami/kafka/docker-compose-cluster.yml
version: "3.8"

services:
  kafka0:
    image: docker.io/bitnami/kafka:3.5
    ports:
      - 9092:9092
    expose:
      - 9093
      - 9099
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka0:9093,1@kafka1:9093,2@kafka2:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      # Listeners
      - KAFKA_CFG_LISTENERS=CONTROLLER://kafka0:9093,INTERNAL://kafka0:9099,EXTERNAL://kafka0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka0:9099,EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
    volumes:
      - kafka_0_data:/bitnami/kafka
  kafka1:
    image: docker.io/bitnami/kafka:3.5
    ports:
      - 19092:9092
    expose:
      - 9093
      - 9099
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka0:9093,1@kafka1:9093,2@kafka2:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      # Listeners
      - KAFKA_CFG_LISTENERS=CONTROLLER://kafka1:9093,INTERNAL://kafka1:9099,EXTERNAL://kafka1:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka1:9099,EXTERNAL://localhost:19092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
    volumes:
      - kafka_1_data:/bitnami/kafka
  kafka2:
    image: docker.io/bitnami/kafka:3.5
    ports:
      - 29092:9092
    expose:
      - 9093
      - 9099
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka0:9093,1@kafka1:9093,2@kafka2:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      # Listeners
      - KAFKA_CFG_LISTENERS=CONTROLLER://kafka2:9093,INTERNAL://kafka2:9099,EXTERNAL://kafka2:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka2:9099,EXTERNAL://localhost:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
    volumes:
      - kafka_2_data:/bitnami/kafka

volumes:
  kafka_0_data:
    #driver: local
  kafka_1_data:
    #driver: local
  kafka_2_data:
    #driver: local
